---
version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    command: sh -c "go run *.go"
    volumes:
      - ./app:/go
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=weight_tracker
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
