---
version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    command: sh -c "go run *.go"
    volumes:
      - ./app:/go
    ports:
      - "8081:8081"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=weight_tracker
    volumes:
      - db-data:/var/lib/postgresql/data
  front:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./front:/usr/src/app
    stdin_open: true
    ports:
      - "8080:8080"
    command: sh -c "yarn start"
volumes:
  db-data:
